apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: macross-prod
  name: compro-prod
  labels:
    app: compro-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compro-prod
  template:
    metadata:
      labels:
        app: compro-prod
    spec:
      containers:
      - name: compro-prod
        image: hansenfernando/landing-prod:latest
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  namespace: macross-prod      
  name: compro-svc-prod
spec:
  selector:
    app: compro-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: macross-prod
  name: compro-ingress-prod
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "compro-prod-cookie"
     nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
     nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/affinity-mode: persistent
     nginx.ingress.kubernetes.io/session-cookie-hash: sha1
spec:
  rules:
  - host: hansen.hansenfernando.xyz      
    http:
      paths:
        - backend:
             serviceName: compro-svc-prod
             servicePort: 80
