apiVersion: v1
kind: Namespace
metadata:
  name: cilsy-prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cilsy-prod
  name: compro-prod
  labels:
    app: compro-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compro-prod
  template:
    metadata:
      labels:
        app: compro-prod
    spec:
      containers:
      - name: compro-prod
        image: hansenfernando/landing-prod:latest
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  namespace: cilsy-prod       
  name: compro-svc-prod
spec:
  selector:
    app: compro-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: cilsy-prod
  name: compro-ingress-prod
spec:
  rules:
  - host: *      
    http:
      paths:
      - backend:
          serviceName: compro-svc-prod
          servicePort: 80
